"""Reference data for the router's C encoder (bge-small-en-v1.5), produced with the Hugging Face
tokenizer and PyTorch (run in the recursant-privacy-eval container on gx11, offline).

1. core/src/context/wordpiece_tables.h: Unicode tables that reproduce the BertNormalizer
   (clean_text, handle_chinese_chars, strip_accents, lowercase) and BertPreTokenizer
   (whitespace and punctuation) of the model's tokenizer.json:
   - removed: U+0000, U+FFFD and "other" categories (Cc Cf Cs Co Cn) except \\t \\n \\r;
   - space: \\t \\n \\r and White_Space characters (become ' ');
   - punct: ASCII punctuation and Unicode P* categories (split as single tokens);
   - cjk: the BERT CJK ranges (surrounded by spaces);
   - fold: code point -> UTF-8 of lower(remove Mn(NFD(c))) where that differs from c
     (Hangul syllables are decomposed algorithmically in C instead).
2. A parity fixture: texts with expected token ids (truncated to 512 with [CLS]/[SEP]) and,
   for a subset, the CLS embedding (L2-normalized) from PyTorch.
usage: python3 encoder_reference.py MODEL_DIR TEXTS.jsonl OUT_TABLES.h OUT_FIXTURE.jsonl [N_EMB]"""
import json, sys, unicodedata
import torch
from transformers import AutoModel, AutoTokenizer

model_dir, texts_path, out_h, out_fix = sys.argv[1:5]
n_emb = int(sys.argv[5]) if len(sys.argv) > 5 else 64

CJK = [(0x4E00, 0x9FFF), (0x3400, 0x4DBF), (0x20000, 0x2A6DF), (0x2A700, 0x2B73F), (0x2B740, 0x2B81F),
       (0x2B820, 0x2CEAF), (0xF900, 0xFAFF), (0x2F800, 0x2FA1F)]


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        if pred(cp):
            if start is None: start = cp
        elif start is not None:
            out.append((start, cp - 1)); start = None
    if start is not None: out.append((start, 0x10FFFF))
    return out


def removed(cp):
    if cp in (9, 10, 13): return False
    if cp in (0, 0xFFFD): return True
    return unicodedata.category(chr(cp)).startswith('C')


def space(cp):
    return cp in (9, 10, 13) or (not removed(cp) and chr(cp).isspace())


def punct(cp):
    return (33 <= cp <= 47 or 58 <= cp <= 64 or 91 <= cp <= 96 or 123 <= cp <= 126) or unicodedata.category(chr(cp)).startswith('P')


def fold(cp):
    c = chr(cp)
    s = ''.join(ch for ch in unicodedata.normalize('NFD', c) if unicodedata.category(ch) != 'Mn')
    return s.lower()


def c_ranges(name, rs):
    body = ',\n'.join('    {0x%X,0x%X}' % r for r in rs)
    return 'static const uint32_t %s[][2]={\n%s\n};\n#define %s_N %d\n' % (name, body, name.upper(), len(rs))


folds = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF or 0xAC00 <= cp <= 0xD7A3 or removed(cp) or space(cp): continue   # Hangul: decomposed in C
    f = fold(cp)
    if f != chr(cp): folds.append((cp, f.encode('utf-8')))
with open(out_h, 'w') as h:
    h.write('/* Generated by bench/prompt/encoder_reference.py from Python %s unicodedata %s.\n'
            ' * Do not edit. BertNormalizer + BertPreTokenizer character classes for the encoder. */\n'
            '#include <stdint.h>\n' % (sys.version.split()[0], unicodedata.unidata_version))
    h.write(c_ranges('wp_removed', ranges(removed)))
    h.write(c_ranges('wp_space', ranges(space)))
    h.write(c_ranges('wp_punct', ranges(punct)))
    h.write(c_ranges('wp_cjk', CJK))
    h.write('static const struct {uint32_t cp;const char *utf8;} wp_fold[]={\n')
    h.write(',\n'.join('    {0x%X,"%s"}' % (cp, ''.join('\\x%02x' % b for b in f)) for cp, f in folds))
    h.write('\n};\n#define WP_FOLD_N %d\n' % len(folds))
print('tables: %d folds' % len(folds))

tok = AutoTokenizer.from_pretrained(model_dir)
model = AutoModel.from_pretrained(model_dir).eval()
texts = [json.loads(l)['text'] for l in open(texts_path)]
with open(out_fix, 'w') as f, torch.no_grad():
    for i, t in enumerate(texts):
        ids = tok(t, truncation=True, max_length=512)['input_ids']
        row = {'text': t, 'ids': ids}
        if i < n_emb:
            b = tok(t, truncation=True, max_length=512, return_tensors='pt')
            e = torch.nn.functional.normalize(model(**b).last_hidden_state[:, 0], dim=-1)[0]
            row['cls'] = [round(x, 7) for x in e.tolist()]
        f.write(json.dumps(row, ensure_ascii=False) + '\n')
print('fixture: %d texts, %d embeddings' % (len(texts), min(n_emb, len(texts))))
