"""Shared fixtures for discovery integration tests."""

import os
import time
import uuid

import httpx
import pytest


REGISTRY_URL = os.environ.get('REGISTRY_URL', 'http://localhost:5000')
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'admin')
TENANT_ID = 'default'

# Whether agents are deployed in K8s (DISCOVERY_K8S=1) or Docker Compose (DISCOVERY_TOPOLOGY_UP=1)
USE_K8S = os.environ.get('DISCOVERY_K8S', '').lower() in ('1', 'true', 'yes')
USE_DOCKER_COMPOSE = os.environ.get('DISCOVERY_TOPOLOGY_UP', '').lower() in ('1', 'true', 'yes')
TOPOLOGY_AVAILABLE = USE_K8S or USE_DOCKER_COMPOSE

# K8s service DNS names for each discovery group (svc.namespace.svc.cluster.local)
# These match the Service names generated by the Helm chart.
K8S_NAMESPACE = os.environ.get('DISCOVERY_K8S_NAMESPACE', 'recursant')

# Service name prefix used by the Helm chart
_SVC_PREFIX = 'disc'

# Helper to build service FQDN
def _svc(name, port):
    return f'{_SVC_PREFIX}-{name}.{K8S_NAMESPACE}.svc.cluster.local:{port}'

# Engineering group (15 agents)
DISC_ENG_SERVICES = [
    _svc('eng-ci-pipeline', 5100),
    _svc('eng-code-review', 5101),
    _svc('eng-debug-assistant', 5102),
    _svc('eng-deploy', 5103),
    _svc('eng-deployment-bot', 5104),
    _svc('eng-doc-generator', 5105),
    _svc('eng-log-analyzer', 5106),
    _svc('eng-perf-monitor', 5107),
    _svc('eng-research', 5108),
    _svc('eng-security-scanner', 5109),
    _svc('eng-translator', 5110),
    _svc('eng-summarizer', 5111),
    _svc('eng-crew-planner', 5112),
    _svc('eng-legacy-api', 5113),
    _svc('eng-test-runner', 5114),
]

# Data Science group (12 agents)
DISC_DS_SERVICES = [
    _svc('ds-analysis', 5200),
    _svc('ds-data-cleaner', 5201),
    _svc('ds-feature-eng', 5202),
    _svc('ds-model-registry', 5203),
    _svc('ds-experiment-tracker', 5204),
    _svc('ds-ml-pipeline', 5205),
    _svc('ds-rag-pipeline', 5206),
    _svc('ds-prompt-optimizer', 5207),
    _svc('ds-analysis-crew', 5208),
    _svc('ds-etl-crew', 5209),
    _svc('ds-embedding-svc', 5210),
    _svc('ds-grafana-proxy', 5211),
]

# MCP servers (8 agents)
DISC_MCP_SERVICES = [
    _svc('mcp-analytics', 5300),
    _svc('mcp-auth', 5301),
    _svc('mcp-calculator', 5302),
    _svc('mcp-database', 5303),
    _svc('mcp-email', 5304),
    _svc('mcp-notifications', 5305),
    _svc('mcp-search', 5306),
    _svc('mcp-storage', 5307),
]

# Partner group (13 agents)
DISC_PARTNER_SERVICES = [
    _svc('partner-billing', 5400),
    _svc('partner-compliance-checker', 5401),
    _svc('partner-crm-connector', 5402),
    _svc('partner-invoice-bot', 5403),
    _svc('partner-order-tracker', 5404),
    _svc('partner-payment-gateway', 5405),
    _svc('partner-shipping-agent', 5406),
    _svc('partner-audit-logger', 5407),
    _svc('partner-erp-bridge', 5408),
    _svc('partner-inventory-sync', 5409),
    _svc('partner-legacy-soap', 5410),
    _svc('partner-flaky-service', 5411),
    _svc('partner-secure-vault', 5412),
]

# Isolated group (2 agents)
DISC_ISO_SERVICES = [
    _svc('isolated-honeypot', 9999),
    _svc('isolated-sandbox', 12345),
]

# All services combined
DISC_ALL_SERVICES = (
    DISC_ENG_SERVICES + DISC_DS_SERVICES + DISC_MCP_SERVICES
    + DISC_PARTNER_SERVICES + DISC_ISO_SERVICES
)

# Organized by group for easy test access
DISC_SERVICES = {
    'eng': DISC_ENG_SERVICES,
    'ds': DISC_DS_SERVICES,
    'mcp': DISC_MCP_SERVICES,
    'partner': DISC_PARTNER_SERVICES,
    'iso': DISC_ISO_SERVICES,
    'all': DISC_ALL_SERVICES,
}

# Legacy CIDR-based subnets (Docker Compose topology)
LEGACY_SUBNETS = {
    'a': '172.30.1.0/24',
    'b': '172.30.2.0/24',
    'c': '172.30.3.0/24',
    'd': '172.30.4.0/24',
    'e': '172.30.5.0/24',
}


@pytest.fixture(scope='session')
def auth_headers():
    """Get JWT token from registry login."""
    resp = httpx.post(
        f'{REGISTRY_URL}/v1/auth/login',
        json={'username': 'admin', 'password': ADMIN_PASSWORD},
        timeout=10,
    )
    assert resp.status_code == 200, f'Login failed: {resp.text}'
    token = resp.json()['token']
    return {
        'Authorization': f'Bearer {token}',
        'X-Tenant-ID': TENANT_ID,
        'Content-Type': 'application/json',
    }


@pytest.fixture
def api(auth_headers):
    """HTTP client with auth headers."""
    return httpx.Client(
        base_url=f'{REGISTRY_URL}/v1',
        headers=auth_headers,
        timeout=30,
    )


@pytest.fixture
def cleanup_scans(api):
    """Track created scans for cleanup."""
    scan_ids = []
    yield scan_ids
    # Cleanup: cancel any running scans
    for sid in scan_ids:
        try:
            api.delete(f'/discovery/scans/{sid}')
        except Exception:
            pass


@pytest.fixture
def reset_agent_statuses():
    """Reset all discovered agents/tools to 'unknown'/'ungoverned' AND clean up
    Agent records created by previous onboard calls so tests are idempotent."""
    from app import create_app, db
    from app.models.discovery import DiscoveredAgent, DiscoveredTool
    from app.models.agent import Agent, Capability
    from datetime import datetime, timezone

    app = create_app()
    with app.app_context():
        # Soft-delete any Agent records created by the discovery onboarding flow
        Agent.query.filter(
            Agent.owner_id == 'discovery-service',
            Agent.deleted_at.is_(None),
        ).update({'deleted_at': datetime.now(timezone.utc)})

        # Reset discovered agents/tools back to ungoverned state
        DiscoveredAgent.query.update({'governance_status': 'unknown', 'registry_agent_id': None})
        DiscoveredTool.query.update({'governance_status': 'ungoverned', 'mesh_tool_id': None})
        db.session.commit()


def scan_and_wait(api, scan_data, timeout=120):
    """Create a scan and wait for completion."""
    resp = api.post('/discovery/scans', json=scan_data)
    assert resp.status_code == 201, f'Failed to create scan: {resp.text}'
    scan_id = resp.json()['id']

    deadline = time.time() + timeout
    while time.time() < deadline:
        resp = api.get(f'/discovery/scans/{scan_id}')
        assert resp.status_code == 200
        status = resp.json()['status']
        if status in ('completed', 'failed', 'cancelled'):
            return resp.json()
        time.sleep(1)

    raise TimeoutError(f'Scan {scan_id} did not complete within {timeout}s')


# Markers
def pytest_configure(config):
    config.addinivalue_line('markers', 'requires_topology: needs 50-container simulator running')
    config.addinivalue_line('markers', 'slow: takes >30s')
    config.addinivalue_line('markers', 'destructive: stops/restarts containers')


def pytest_collection_modifyitems(config, items):
    """Auto-skip requires_topology tests when topology is not available."""
    if not TOPOLOGY_AVAILABLE:
        skip_topo = pytest.mark.skip(reason='Topology not running (set DISCOVERY_K8S=1 or DISCOVERY_TOPOLOGY_UP=1)')
        for item in items:
            if 'requires_topology' in item.keywords:
                item.add_marker(skip_topo)
