/* Generated by tools/logo.py; do not edit by hand. */
#ifndef RECURSANT_LOGO_ART_H
#define RECURSANT_LOGO_ART_H
#define RC_LOGO_ROWS 6
#define RC_LOGO_WIDTH 76
#define RC_EMBLEM_ROWS 12
#define RC_EMBLEM_WIDTH 26
#define RC_LOGO_GAP 3
#define RC_LOGO_SHADOW_PCT 42
#define RC_LOGO_STOPS 4
#define RC_LOGO_TAGLINE "the agent-aware model router"
static const char *const rc_logo_rows[RC_LOGO_ROWS] = {
    "██████╗ ███████╗ ██████╗██╗   ██╗██████╗ ███████╗ █████╗ ███╗   ██╗████████╗",
    "██╔══██╗██╔════╝██╔════╝██║   ██║██╔══██╗██╔════╝██╔══██╗████╗  ██║╚══██╔══╝",
    "██████╔╝█████╗  ██║     ██║   ██║██████╔╝███████╗███████║██╔██╗ ██║   ██║   ",
    "██╔══██╗██╔══╝  ██║     ██║   ██║██╔══██╗╚════██║██╔══██║██║╚██╗██║   ██║   ",
    "██║  ██║███████╗╚██████╗╚██████╔╝██║  ██║███████║██║  ██║██║ ╚████║   ██║   ",
    "╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ",
};
static const char *const rc_emblem_rows[RC_EMBLEM_ROWS] = {
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣼⣿⣿⣿⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣤⣤⡶⠟⠋⠁⠉⠉⠁⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣶⠿⠛⠷⣦⣄⡀⢀⡤⠤⣄⠀",
    "⠀⢀⣀⣀⠀⠀⠀⠀⠀⠀⣠⣴⡿⠋⠁⠀⠀⠀⠀⠉⠛⢿⠆⠀⢸⠀",
    "⡰⢉⣤⣌⠱⡤⠤⢤⣴⡾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠓⠒⠋⠀",
    "⠱⣈⠛⢋⡰⠉⠉⠙⠻⢷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀",
    "⠀⠈⠉⠉⠀⠀⠀⠀⠀⠀⠉⠻⣷⣤⡀⠀⠀⠀⠀⠀⣀⣼⣿⣿⣿⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠿⣶⣤⣤⡶⠟⠋⠁⠉⠉⠁⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⠷⣦⣄⡀⢀⡤⠤⣄⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⢿⠆⠀⢸⠀",
    "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠓⠒⠋⠀",
};
/* Left-to-right gradient stops (emblem through the last letter). */
static const unsigned char rc_logo_stops[RC_LOGO_STOPS][3] = {
    {0, 245, 212},
    {0, 187, 249},
    {58, 134, 255},
    {131, 56, 236},
};
#endif
