{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recursant.fullname" . }}-webhook
  namespace: {{ include "recursant.namespace" . }}
  labels:
    {{- include "recursant.labels" . | nindent 4 }}
    app: {{ include "recursant.fullname" . }}-webhook
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: {{ include "recursant.fullname" . }}-webhook
{{- end }}
