#!/usr/bin/env python3
"""Recursant logo: ANSI Shadow letters plus a braille emblem (a recursive routing
tree: one request from the agent, fanning out to many destinations).

Writes core/src/cli/logo_art.h (what the CLI prints) and, when Pillow is present,
docs/assets/recursant-logo.png (the README image). Run from the repo root:

    python3 tools/logo.py
"""
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GLYPHS = {
    'R': ["██████╗ ", "██╔══██╗", "██████╔╝", "██╔══██╗", "██║  ██║", "╚═╝  ╚═╝"],
    'E': ["███████╗", "██╔════╝", "█████╗  ", "██╔══╝  ", "███████╗", "╚══════╝"],
    'C': [" ██████╗", "██╔════╝", "██║     ", "██║     ", "╚██████╗", " ╚═════╝"],
    'U': ["██╗   ██╗", "██║   ██║", "██║   ██║", "██║   ██║", "╚██████╔╝", " ╚═════╝ "],
    'S': ["███████╗", "██╔════╝", "███████╗", "╚════██║", "███████║", "╚══════╝"],
    'A': [" █████╗ ", "██╔══██╗", "███████║", "██╔══██║", "██║  ██║", "╚═╝  ╚═╝"],
    'N': ["███╗   ██╗", "████╗  ██║", "██╔██╗ ██║", "██║╚██╗██║", "██║ ╚████║", "╚═╝  ╚═══╝"],
    'T': ["████████╗", "╚══██╔══╝", "   ██║   ", "   ██║   ", "   ██║   ", "   ╚═╝   "],
}
# One colour per letter row: teal -> cyan -> azure -> indigo -> violet.
COLORS = ["#00F5D4", "#00DDEB", "#00BBF9", "#3A86FF", "#6A4CFF", "#8338EC"]
TAGLINE = "the agent-aware model router"


def letters(word="RECURSANT"):
    for k, rows in GLYPHS.items():
        assert len({len(r) for r in rows}) == 1, k
    return ["".join(GLYPHS[c][i] for c in word) for i in range(6)]


def emblem(cols=26, rows=12):
    w, h = cols * 2, rows * 4  # a braille cell is 2 x 4 dots
    dots = [[False] * w for _ in range(h)]

    def plot(x, y):
        xi, yi = int(round(x)), int(round(y))
        if 0 <= xi < w and 0 <= yi < h:
            dots[yi][xi] = True

    def line(x0, y0, x1, y1):
        n = int(max(abs(x1 - x0), abs(y1 - y0)) * 2) + 1
        for i in range(n + 1):
            t = i / n
            plot(x0 + (x1 - x0) * t, y0 + (y1 - y0) * t)

    def disc(cx, cy, r):
        for yy in range(int(cy - r) - 1, int(cy + r) + 2):
            for xx in range(int(cx - r) - 1, int(cx + r) + 2):
                if (xx - cx) ** 2 + (yy - cy) ** 2 <= r * r:
                    plot(xx, yy)

    def ring(cx, cy, r):
        for k in range(64):
            a = 2 * math.pi * k / 64
            plot(cx + r * math.cos(a), cy + r * math.sin(a))

    def branch(x, y, length, spread, depth):
        if depth == 0:
            disc(x, y, 2.0)
            return
        for sign in (-1, 1):
            nx, ny = x + length, y + sign * spread
            line(x, y, nx, ny)
            branch(nx, ny, length * 0.8, spread / 2, depth - 1)
        disc(x, y, 1.4)

    cy = (h - 1) / 2
    ring(4, cy, 3.2)
    disc(4, cy, 1.2)            # the agent
    line(6, cy, 13, cy)         # one request in
    branch(13, cy, 13, 12, 3)   # many places it can go
    bits = ((0, 0, 0x01), (0, 1, 0x02), (0, 2, 0x04), (1, 0, 0x08),
            (1, 1, 0x10), (1, 2, 0x20), (0, 3, 0x40), (1, 3, 0x80))
    out = []
    for y in range(0, h, 4):
        row = ""
        for x in range(0, w, 2):
            v = sum(b for dx, dy, b in bits if dots[y + dy][x + dx])
            row += chr(0x2800 + v)
        out.append(row)
    return out


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_header(path, let, emb):
    rgb = [tuple(int(c[i:i + 2], 16) for i in (1, 3, 5)) for c in COLORS]
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/logo.py; do not edit by hand. */\n")
        f.write("#ifndef RECURSANT_LOGO_ART_H\n#define RECURSANT_LOGO_ART_H\n")
        f.write(f"#define RC_LOGO_ROWS {len(let)}\n#define RC_LOGO_WIDTH {len(let[0])}\n")
        f.write(f"#define RC_EMBLEM_ROWS {len(emb)}\n#define RC_EMBLEM_WIDTH {len(emb[0])}\n")
        f.write(f"#define RC_LOGO_TAGLINE {c_string(TAGLINE)}\n")
        f.write("static const char *const rc_logo_rows[RC_LOGO_ROWS] = {\n")
        f.writelines(f"    {c_string(r)},\n" for r in let)
        f.write("};\nstatic const char *const rc_emblem_rows[RC_EMBLEM_ROWS] = {\n")
        f.writelines(f"    {c_string(r)},\n" for r in emb)
        f.write("};\nstatic const unsigned char rc_logo_rgb[RC_LOGO_ROWS][3] = {\n")
        f.writelines(f"    {{{r}, {g}, {b}}},\n" for r, g, b in rgb)
        f.write("};\n#endif\n")


def write_png(path, let, emb):
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("Pillow not installed: skipped", path)
        return
    font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf", 28)
    small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 26)
    cw, ch, pad = int(font.getbbox("█")[2]), 33, 36
    width = (len(emb[0]) + 3 + len(let[0])) * cw + 2 * pad
    height = len(emb) * ch + 2 * pad
    img = Image.new("RGB", (width, height), (13, 17, 23))
    g = ImageDraw.Draw(img)
    bits = ((0, 0, 1), (0, 1, 2), (0, 2, 4), (1, 0, 8), (1, 1, 16), (1, 2, 32), (0, 3, 64), (1, 3, 128))
    r = cw / 5.5
    for i, row in enumerate(emb):
        colour = COLORS[min(len(COLORS) - 1, i * len(COLORS) // len(emb))]
        for j, c in enumerate(row):
            v = ord(c) - 0x2800
            for dx, dy, b in bits:
                if v & b:
                    x = pad + j * cw + dx * cw / 2 + cw / 4
                    y = pad + i * ch + dy * ch / 4 + ch / 8
                    g.ellipse((x - r, y - r, x + r, y + r), fill=colour)
    x0 = pad + (len(emb[0]) + 3) * cw
    top = pad + (len(emb) - len(let) - 2) // 2 * ch
    for i, row in enumerate(let):
        g.text((x0, top + i * ch), row, font=font, fill=COLORS[i])
    g.text((x0 + 2, top + (len(let) + 1) * ch), TAGLINE, font=small, fill=(139, 148, 158))
    img.save(path, optimize=True)


def main():
    let, emb = letters(), emblem()
    header = os.path.join(ROOT, "core/src/cli/logo_art.h")
    png = os.path.join(ROOT, "docs/assets/recursant-logo.png")
    os.makedirs(os.path.dirname(png), exist_ok=True)
    write_header(header, let, emb)
    write_png(png, let, emb)
    if "--print" in sys.argv:
        print("\n".join(e + "   " + (let[i - 3] if 3 <= i < 9 else "") for i, e in enumerate(emb)))
    print("wrote", header, "and", png)


if __name__ == "__main__":
    main()
