from app.schemas.agent import (
    AgentSchema,
    AgentCreateSchema,
    AgentUpdateSchema,
    AgentVersionSchema,
    AgentListSchema,
    CapabilitySchema,
    EndpointSchema,
    ResourceQuotaSchema,
    ToolDependencySchema,
)
from app.schemas.security import (
    # Test case schemas
    SecurityTestCaseSchema,
    SecurityTestCaseCreateSchema,
    SecurityTestCaseUpdateSchema,
    SecurityTestCaseListSchema,
    # Policy schemas
    SecurityPolicySchema,
    SecurityPolicyCreateSchema,
    SecurityPolicyUpdateSchema,
    SecurityPolicyListSchema,
    # Scan schemas
    SecurityScanSchema,
    SecurityScanTriggerSchema,
    SecurityScanListSchema,
    # Result schemas
    SecurityScanResultSchema,
    SecurityScanResultListSchema,
    # Nested schemas
    DetectionPatternsSchema,
    ScanConfigSchema,
)
from app.schemas.evaluation import (
    # Nested schemas
    JudgeConfigSchema,
    GradingCriterionSchema,
    # Test case schemas
    EvaluationTestCaseSchema,
    EvaluationTestCaseCreateSchema,
    EvaluationTestCaseUpdateSchema,
    EvaluationTestCaseListSchema,
    # Suite schemas
    EvaluationSuiteSchema,
    EvaluationSuiteCreateSchema,
    EvaluationSuiteUpdateSchema,
    EvaluationSuiteListSchema,
    # Evaluation schemas
    EvaluationSchema,
    EvaluationTriggerSchema,
    EvaluationListSchema,
    # Result schemas
    EvaluationResultSchema,
    EvaluationResultListSchema,
)

from app.schemas.audit import (
    AuditLogSchema,
    AuditLogListSchema,
)

from app.schemas.mesh import (
    MeshRegisterSchema,
    MeshHeartbeatSchema,
    MeshDeregisterSchema,
    MeshRegistrationSchema,
    MeshDiscoverAgentSchema,
    MeshPolicyCreateSchema,
    MeshPolicySchema,
    MeshPolicyListSchema,
    MeshAuditRecordSchema,
    MeshAuditSubmitSchema,
    MeshAuditLogSchema,
)

from app.schemas.guardrail import (
    GuardrailCreateSchema,
    GuardrailUpdateSchema,
    GuardrailSchema,
    GuardrailListSchema,
    GuardrailAssignmentCreateSchema,
    GuardrailAssignmentSchema,
    GuardrailTestRunCreateSchema,
    GuardrailTestRunSchema,
    GuardrailForSidecarSchema,
)

from app.schemas.adversarial import (
    AdversarialTestSuiteCreateSchema,
    AdversarialTestSuiteUpdateSchema,
    AdversarialTestSuiteSchema,
    AdversarialTestSuiteListSchema,
    AdversarialTestRunSchema,
    AdversarialTestRunListSchema,
)

from app.schemas.user import (
    UserSchema,
    UserCreateSchema,
    UserUpdateSchema,
    UserListSchema,
    UserGroupSchema,
    UserGroupAssignSchema,
    GroupSchema,
    GroupCreateSchema,
    GroupUpdateSchema,
    GroupListSchema,
)

from app.schemas.discovery import (
    ScanConfigSchema as DiscoveryScanConfigSchema,
    DiscoveryScanCreateSchema,
    DiscoveryScanSchema,
    DiscoveryScanListSchema,
    DiscoveredHostSchema,
    DiscoveredAgentSchema,
    DiscoveredAgentListSchema,
    DiscoveredToolSchema,
    DiscoveredToolListSchema,
    OnboardAgentSchema,
    BulkOnboardSchema,
    OnboardToolSchema,
    DiscoveryScanScheduleSchema,
    DiscoveryScanScheduleCreateSchema,
    DiscoveryStatsSchema,
)

from app.schemas.euai import (
    EUAIClassificationSchema,
    EUAIClassificationCreateSchema,
    EUAIClassificationUpdateSchema,
    ComplianceRequirementSchema,
    ComplianceStatusSchema,
    ComplianceStatusUpdateSchema,
    AnnexIVDocumentSchema,
    AnnexIVDocumentListSchema,
    AnnexIVManualSectionsUpdateSchema,
    ConformityAssessmentSchema,
    ConformityAssessmentCreateSchema,
    ConformityFindingSchema,
    PostMarketMonitoringPlanSchema,
    PostMarketMonitoringPlanCreateSchema,
    PostMarketMonitoringReportSchema,
    GapAnalysisItemSchema,
    GapAnalysisSchema,
    ComplianceDashboardAgentSchema,
    ComplianceDashboardSchema,
)

__all__ = [
    # Agent schemas
    'AgentSchema',
    'AgentCreateSchema',
    'AgentUpdateSchema',
    'AgentVersionSchema',
    'AgentListSchema',
    'CapabilitySchema',
    'EndpointSchema',
    'ResourceQuotaSchema',
    'ToolDependencySchema',
    # Security test case schemas
    'SecurityTestCaseSchema',
    'SecurityTestCaseCreateSchema',
    'SecurityTestCaseUpdateSchema',
    'SecurityTestCaseListSchema',
    # Security policy schemas
    'SecurityPolicySchema',
    'SecurityPolicyCreateSchema',
    'SecurityPolicyUpdateSchema',
    'SecurityPolicyListSchema',
    # Security scan schemas
    'SecurityScanSchema',
    'SecurityScanTriggerSchema',
    'SecurityScanListSchema',
    # Scan result schemas
    'SecurityScanResultSchema',
    'SecurityScanResultListSchema',
    # Nested schemas
    'DetectionPatternsSchema',
    'ScanConfigSchema',
    # Evaluation schemas
    'JudgeConfigSchema',
    'GradingCriterionSchema',
    'EvaluationTestCaseSchema',
    'EvaluationTestCaseCreateSchema',
    'EvaluationTestCaseUpdateSchema',
    'EvaluationTestCaseListSchema',
    'EvaluationSuiteSchema',
    'EvaluationSuiteCreateSchema',
    'EvaluationSuiteUpdateSchema',
    'EvaluationSuiteListSchema',
    'EvaluationSchema',
    'EvaluationTriggerSchema',
    'EvaluationListSchema',
    'EvaluationResultSchema',
    'EvaluationResultListSchema',
    # User/Group schemas
    'UserSchema',
    'UserCreateSchema',
    'UserUpdateSchema',
    'UserListSchema',
    'UserGroupSchema',
    'UserGroupAssignSchema',
    'GroupSchema',
    'GroupCreateSchema',
    'GroupUpdateSchema',
    'GroupListSchema',
    # Audit schemas
    'AuditLogSchema',
    'AuditLogListSchema',
    # Guardrail schemas
    'GuardrailCreateSchema',
    'GuardrailUpdateSchema',
    'GuardrailSchema',
    'GuardrailListSchema',
    'GuardrailAssignmentCreateSchema',
    'GuardrailAssignmentSchema',
    'GuardrailTestRunCreateSchema',
    'GuardrailTestRunSchema',
    'GuardrailForSidecarSchema',
    # Mesh schemas
    'MeshRegisterSchema',
    'MeshHeartbeatSchema',
    'MeshDeregisterSchema',
    'MeshRegistrationSchema',
    'MeshDiscoverAgentSchema',
    'MeshPolicyCreateSchema',
    'MeshPolicySchema',
    'MeshPolicyListSchema',
    'MeshAuditRecordSchema',
    'MeshAuditSubmitSchema',
    'MeshAuditLogSchema',
    # Adversarial schemas
    'AdversarialTestSuiteCreateSchema',
    'AdversarialTestSuiteUpdateSchema',
    'AdversarialTestSuiteSchema',
    'AdversarialTestSuiteListSchema',
    'AdversarialTestRunSchema',
    'AdversarialTestRunListSchema',
    # Discovery schemas
    'DiscoveryScanConfigSchema',
    'DiscoveryScanCreateSchema',
    'DiscoveryScanSchema',
    'DiscoveryScanListSchema',
    'DiscoveredHostSchema',
    'DiscoveredAgentSchema',
    'DiscoveredAgentListSchema',
    'DiscoveredToolSchema',
    'DiscoveredToolListSchema',
    'OnboardAgentSchema',
    'BulkOnboardSchema',
    'OnboardToolSchema',
    'DiscoveryScanScheduleSchema',
    'DiscoveryScanScheduleCreateSchema',
    'DiscoveryStatsSchema',
    # EU AI Act compliance schemas
    'EUAIClassificationSchema',
    'EUAIClassificationCreateSchema',
    'EUAIClassificationUpdateSchema',
    'ComplianceRequirementSchema',
    'ComplianceStatusSchema',
    'ComplianceStatusUpdateSchema',
    'AnnexIVDocumentSchema',
    'AnnexIVDocumentListSchema',
    'AnnexIVManualSectionsUpdateSchema',
    'ConformityAssessmentSchema',
    'ConformityAssessmentCreateSchema',
    'ConformityFindingSchema',
    'PostMarketMonitoringPlanSchema',
    'PostMarketMonitoringPlanCreateSchema',
    'PostMarketMonitoringReportSchema',
    'GapAnalysisItemSchema',
    'GapAnalysisSchema',
    'ComplianceDashboardAgentSchema',
    'ComplianceDashboardSchema',
]
